name: Deploy to Development Dev
on:
  push:
    branches: [development-dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Deploy static files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEVELOPMENT_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEVELOPMENT_DEV_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DEVELOPMENT_DEV_DISTRIBUTION_ID }}
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
          npm ci
          npm test
          npm audit
          npm run build
          cd ./html
          # fail the build if any generated javascript contains 'eval' to help mitigate the need for script-src unsafe-eval CSP
          grep -l eval static/*.js && exit 99
          aws s3 sync ./static/ s3://brave-development-devtalk-origin/static/ --cache-control "max-age=31536000, public"
          aws s3 sync . s3://brave-development-devtalk-origin/ --exclude "static/*" --cache-control "max-age=60, public"
          INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" | jq -r '.Invalidation.Id')
          aws cloudfront wait invalidation-completed --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --id $INVALIDATION_ID
